### ISSUE TITLE
koa-router Router#all

### ISSUE THREAD

**Issue by pschwyter** [turnstyle/koa-tiny-router#3]
I was going over the `koa-router` docs and found that the `Router` has an `#all` method which maps a request to a route for any method.

example:
```js
router.all('/account/:accountId', accountController.handle.bind(accountController))
```

I tested it out and it works like a charm.

As much as I want our own neat little router, is it still justified?

**Comment by evert** [comment]
that makes it a lot less interesting =(

**Comment by evert** [comment]
boo

**Comment by pschwyter** [comment]
yeah :(

**Comment by evert** [comment]
It becomes a lot less needed. koa-router clearly already does it, but it might still be nice to have a super-minimal router (less code and all). I'll leave it up to you. Fine either way.

**Comment by evert** [comment]
If you don't want to continue, lets delete this project though

**Comment by pschwyter** [comment]
Maybe I'll just fork it and work on it during spurts of inspiration. More of a novelty thing than anything else to see how small the router can get. But yeah, let's stop work on this for our purposes.
